name: PUB400 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Install SSH and sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client sshpass

    - name: Run Commands on PUB400
      env:
        PUB400_USERNAME: ${{ secrets.PUB400_USERNAME }}
        PUB400_PASSWORD: ${{ secrets.PUB400_PASSWORD }}
        PUB400_HOST: ${{ secrets.PUB400_HOST }}
      run: | 
        sshpass -p "$PUB400_PASSWORD" ssh -o StrictHostKeyChecking=no -p 2222 $PUB400_USERNAME@$PUB400_HOST "git --version && pwd && cd /home/ravi1/cmpsys && export CURLIB=RAVI1 && makei build"
